### ISSUE TITLE
how to you flash the fip.bin?

### ISSUE THREAD

**Issue by unicornx** [0x754C/sg200x-bare#1]
After we create the fip.bin, how to flash it into sd-card?
I cp the fip.bin into the first partition of the sd-card, but cannot boot.

**Comment by 0x754C** [comment]
use usb flash it

**Comment by 0x754C** [comment]
sdcard must be MBR partition table, first partition type must be 0x0E, bootable, FAT filesystem

**Comment by 0x754C** [comment]
you can also use usb cable download fip.bin in sram & run it.

use command:

```
make flash
```

**Comment by unicornx** [comment]
thanks, I will close this issue.
